name: Use Bright API Scan

on:
  workflow_dispatch:

jobs:
  call-bright-scan:
    uses: mfeferman-bs/bright-api-scan/.github/workflows/bright-api-incremental-scan.yml@v1  # or a specific tag like @v1.0.0
    with:
      archive_path: ./swagger.json
      scan_name: "Incremental API Scan"
    secrets:
      BRIGHT_API_TOKEN: ${{ secrets.BRIGHT_API_TOKEN }}
      BRIGHT_PROJECT_ID: ${{ secrets.BRIGHT_PROJECT_ID }}
      KEY_GITHUB: ${{ secrets.GITHUB_TOKEN }}
